### ISSUE TITLE
The server cannot be started

### ISSUE THREAD

**Issue by SAGUMEDREAM** [MincraftEinstein/WhitePumpkins#1]
You didn't separate the client and server code? Server-side shouldn't call rendering, right?

31.10 13:03:33 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/render/entity/EntityRendererFactory
31.10 13:03:33 [Server] INFO at einstein.white_pumpkins.WhitePumpkinsFabric.onInitialize(WhitePumpkinsFabric.java:49) ~[WhitePumpkins-fabric-1.21.1-1.0.0.jar:?]
31.10 13:03:33 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]

**Comment by MincraftEinstein** [comment]
Yes, you're right, I accidentally added a line of code the the wrong place.
